name: Package Addon

on:
  release:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create Package
        uses: BigWigsMods/packager@master
      - name: Debug
        run: |
          cd .release
          tree
